name: Félhét
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16666
title: f7sailing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#29a5a7'
    - '#afcfdc'
    - '#175d67'
    - '#d7a393'
  brandStrength: 0.6334415250457823
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
